[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "zeno"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai>=3.13.0",
    "python-dotenv>=1.2.3",
    "rich>=13",
]

[tool.setuptools.packages.find]
where = ["."]
